# Generated by Django 3.0.1 on 2019-12-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191228_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Subject',
            new_name='grades',
        ),
    ]
