# Generated by Django 3.0.1 on 2019-12-28 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191228_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grades',
            new_name='subjects',
        ),
    ]
